/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    'Hide the top row': '隐藏顶行',
    'Life Points': '生命点',
    'Show a row': '显示一行',
    'Get One Deuterium': '获取 1 氘',
    'Get One Hundred Deuterium': '获取 100 氘',
    'Get Ten Thousand Deuterium': '获取 10000 氘',
    'Get One Million Deuterium': '获取 100万 氘',
    'Shift: Hides top layers until an unfinished layer': 'Shift：隐藏顶层直到未完成的层',
    'Shift: Show all rows': 'Shift：显示所有行',
    'Click': '点击',
    'Get Twenty Hydrogen': '获取 20 氢',
    'Get Ten Million Hydrogen': '获取 1000万 氢',
    'Get One Hundred Billion Hydrogen': '获取 1000亿 氢',
    'Get Four Hundred Hydrogen': '获取 400 氢',
    'Get Eight Thousand Hydrogen': '获取 8000 氢',
    'Get Fifty Thousand Atomic Hydrogen': '获取 50000 原子氢',
    'Get Five Atomic Hydrogen': '获取 5 原子氢',
    'Get Five Hundred Atomic Hydrogen': '获取 500 原子氢',
    'Get Five Million Atomic Hydrogen': '获取 500万 原子氢',
    '1+Achievements multiplies Hydrogen gain': '1+成就乘以氢增益',
    'Currently': '当前',
    'Each upgrade adds 1 to the Hydrogen gain formula': '每次升级氢增益公式都会增加 1',
    'Hydrogen': '氢',
    'ln([best Hydrogen]) multiplies Life Point gain': 'ln([最大氢]) 乘以生命点增益',
    'Raise Hydrogen I to ln([Hydrogen upgrades]': '将氢 I 升至 ln（[氢升级]',
    'Upgrades': '升级',
    ') upgrades, but buying one vastly increases the price of and hides the other': ') 升级，但购买一个会大大增加另一个的价格并隐藏另一个',
    'Deuterium': '氘',
    'H) and Atomic Hydrogen (H': 'H) 和原子氢 (H',
    'ln(ln(10+[best Deuterium])) multiplies Life Point and Hydrogen gain': 'ln(ln(10+[最大氘])) 乘以生命点和氢增益',
    'Search through your Hydrogen to find the special .02% -- Deuterium': '搜索您的氢气以找到特殊的 0.02% -- 氘',
    'Unlock Deuterium (': '解锁 氘 (',
    'Wait for your Hydrogen to cool and bond at a brisk .1% rate': '等待您的氢以 0.1% 的速度冷却并结合',
    'ln([best Deuterium]) multiplies Deuterium gain': 'ln([最大氘]) 乘以氘增益',
    'Raise Deuterium II to the number of upgrades in this row': '将 氘 II 提升至该行的升级数量',
    'Achievement Gotten!': '成就获得！',
    'Atomic Hydrogen': '原子氢',
    'Upgrades in this row ^ .8 raise Hydrogen III effect': '本行升级 ^ .8 提升 氢 III 效果',
    'Make the ln in Hydrogen I a log2': '使氢 I 中的 ln 为 log2',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Nine': '9',
    'Nineteen': '19',
    'One': '1',
    'Seven': '7',
    'Seventeen': '17',
    'Thirteen': '13',
    'Sixteen': '16',
    'Ten': '10',
    'Thirty': '30',
    'eight': '8',
    'five': '5',
    'four': '4',
    'nine': '9',
    'one': '1',
    'seven': '7',
    'six': '6',
    'three': '3',
    'two': '2',
    'Three': '3',
    'Twelve': '12',
    'Twenty': '20',
    'Two': '2',
    'Fourteen': '14',
    'Four': '4',
    'Six': '6',
    'Fifty': '50',
    'Fifteen': '15',
    'Eighteen': '18',
    'Eleven': '11',
    'Eight': '8',
    'Five': '5',
    'Forty': '40',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀
var cnPrefix = {
    "(-": "(-",
    "(+": "(+",
    "(": "(",
    "-": "-",
    "+": "+",
    " ": " ",
    ": ": "： ",
    "\n": "",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": "",
    //树游戏
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Thirty-": "3",
    "Twenty-": "2",
    "Forty-": "4",
    "Fifty-": "5",
    "Hydrogen ": "氢 ",
    "Atomic Hydrogen ": "原子氢 ",
    "Deuterium ": "氘 ",
    "Each upgrade raises Life Point gain ": "每次升级都会提高生命值 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀
var cnPostfix = {
    ":": "：",
    "：": "：",
    ": ": "： ",
    "： ": "： ",
    "/s)": "/s)",
    "/s": "/s",
    ")": ")",
    "%": "%",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "",
    " ": " ",
    "\n": "",
    "/sec": "/秒",
    " nice": " 不错",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^Get ([\d\.,]+) Hydrogen$/, '获得 $1 氢'],
    [/^Get ([\d\.,]+)\^([\d\.,]+) Hydrogen$/, '获得 $1 氢'],
    [/^Get ([\d\.,]+) Carbon$/, '获得 $1 碳'],
    [/^Get ([\d\.,]+)\^([\d\.,]+) Carbon$/, '获得 $1 碳'],
    [/^Get ([\d\.,]+) Oxygen$/, '获得 $1 氧'],
    [/^Get ([\d\.,]+)\^([\d\.,]+) Oxygen$/, '获得 $1 氧'],
    [/^Cost: ([\d\.,]+) Deuterium\n\t\t\t$/, '成本: $1 氘\n\t\t\t'],
    [/^Cost: ([\d\.,]+) Atomic Hydrogen\n\t\t\t$/, '成本: $1 原子氢\n\t\t\t'],
    [/^Cost: ([\d\.,]+) Hydrogen\n\t\t\t$/, '成本: $1 氢\n\t\t\t'],
    [/^([\d\.,]+) Hydrogen$/, '$1 氢'],
    [/^([\d\.,]+) Achievements$/, '$1 成就'],
    [/^You are losing (.+)\% of your Atomic Hydrogen per second$/, '你每秒损失 $1\% 的原子氢'],
    [/^You are losing (.+)\% of your Deuterium per second$/, '你每秒损失 $1\% 的氘'],
    [/^You are losing (.+)\% of your Deuterium per second$/, '你每秒损失 $1\% 的氘'],
    [/^You are gaining (.+) Hydrogen per second$/, '你每秒获得 $1 氢'],
    [/^You are gaining (.+) Deuterium per second$/, '你每秒获得 $1 氘'],
    [/^You have completed the first (.+) rows$/, '您已完成前 $1 行'],
    [/^Last save was: (.+) ago.(.+)$/, '上次保存于： $1 前。$2'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^(\d+) Royal points$/, '$1 皇家点数'],
    [/^Cost: (\d+) RP$/, '成本：$1 皇家点数'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);